name: taskmaster-CI/CD

on:
  push:
    branches:
      - main


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

     -  name: Checkout Repository
        uses: actions/checkout@v4

     -  name: List repository files
        run: ls -la

     -  name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


     -  name: Build Springboot Application
        run: mvn clean package

     -  name: Check Docker version
        run: docker --version

     -  name: Build Docker Image
        run: docker build -t taskmaster:latest .

     -  name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}  
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: ap-south-2

     -  name: Verify credentials
        run: aws sts get-caller-identity

     -  name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

     -  name: Build Docker Image
        run: |
          docker build -t taskmaster:${{ github.sha }} .
          docker tag taskmaster:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/taskmaster:${{ github.sha }}
 

     -  name: Push Docker Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/taskmaster:${{ github.sha }}

     -  name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition taskmaster \
            --query-taskDefinition \
            > taskdefinition.json

     - name: Render New Task Definition
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
        task-definition: task-definition.json
        container-name: taskmaster
        image: ${{ steps.login-ecr.outputs.registry }}/taskmaster:${{ github.sha }}

