name: taskmaster-CI/CD

on:
  push:
    branches:
      - main


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

     -  name: Checkout Repository
        uses: actions/checkout@v4

     -  name: List repository files
        run: ls -la

     -  name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


     -  name: Build Springboot Application
        run: mvn clean package

     -  name: Check Docker version
        run: docker --version



